use_frameworks!

platform :ios, '9.0'

target 'MTABaseViewKit_Example' do
  #pod 'MTABaseViewKit', :path => '../'
  pod 'MTABaseViewKit', :podspec => '../MTABaseViewKit.podspec'

  target 'MTABaseViewKit_Tests' do
    inherit! :search_paths

    pod 'CTMediator'
  end
end
